version: '3'

tasks:
  install:
    aliases:
      - i
    cmds:
      - go install ./cmd/zt

  run:
    cmds:
      - go run ./cmd/zt

  build:
    aliases:
      - b
    cmds:
      - go build -o bin/zt ./cmd/zt

  test:
    aliases:
      - t
    cmds:
      - go test -v ./...
