version: '3'

tasks:
  install:
    aliases:
      - i
    cmds:
      - go install .

  run:
    cmds:
      - go run .

  build:
    aliases:
      - b
    cmds:
      - go build -o bin/zt .

  test:
    aliases:
      - t
    cmds:
      - go test -v ./...
